apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-no-label
  name: test-no-label
spec:
  containers:
  - image: nginx
    name: test-no-label
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
