apiVersion: v1
kind: Pod
metadata:
  labels:
    managed-by: automation
  name: test-with-label
spec:
  containers:
  - image: nginx
    name: test-with-label
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
