apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8srequiredlabels
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredLabels
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredlabels

        violation[{"msg": msg}] {
          input.review.object.kind == "Pod"
          required := "automation"
          provided := object.get(input.review.object.metadata.labels, "managed-by", "")
          provided != required
          msg := sprintf("Pod must have label managed-by=%v", [required])
        }